[pytest]
markers =
    smoke: базовые проверки Movies API
    crud: CRUD операции с фильмами
    filters: тесты фильтрации фильмов
    auth: проверка авторизации и ролей
    db: тесты с проверкой данных в базе данных
    negative: негативные сценарии
    integration: интеграционные тесты